name: chrononote

services:
  database:
    image: postgres:17.6-alpine3.22
    container_name: chrononote-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chrononote
      POSTGRES_USER: cnote
      POSTGRES_PASSWORD: Test1234!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  data:
    driver: local

networks:
  network:
    driver: bridge