@base = http://localhost:5115/api

### Signup API Test
POST {{base}}/auth/signup
Accept: application/json
Content-Type: application/json
{
    "username": "testuser",
    "password": "Test@1234",
    "email": "test.user@email.com"
}

###
